### ISSUE TITLE
What the "number":[0,3000.546684141998,3000.546684141998,0] mean in the sample.czml in the SampleData

### ISSUE THREAD

**Issue by LZS1991** [AnalyticalGraphicsInc/czml-writer#141]
I test the sample.czml in the Cesium\Apps\SampleData,and i want to konw meaning of the number in the leadTime and trailTime. 
I guess that "number":[0,3000.546684141998,3000.546684141998,0] is used to correct the orbit of the satelite after some time.but i am not sure,and i want to know the meaning of the 4 number and how to caculate them.
Thank you....

**Comment by shunter** [comment]
`leadTime` in that file is defined as a sampled property of type number, with two samples.  Please read the https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Structure to understand the structure of CZML.

**Comment by LZS1991** [comment]
I still not find the samples.And i want to know the meaning of the four number and how to create them

**Comment by emackey** [comment]
Hi @LZS1991, questions like this are better asked on the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev).  We use the issue tracker for feature and bug tracking, not general questions.

That said, there's some behavior going on here that may not be spelled out completely.  The `leadTime` and `trailTime` are both times, specified in seconds, for how long the lead and trail path lengths should be.  But some users want a path to start or end at a specific fixed point in time, which is a feature that's not directly available from this lead/trail kind of API.

For example, let's say you had a path that was going to end at exactly 3000.5 seconds after the start time, and you wanted the `leadTime` to reflect the *length of the remaining path* at each moment during a flight.  Since the end time is fixed in time, the `leadTime` decreases as the vehicle flies.  Thus:

```
    "leadTime" : [ 0.0, 3000.5,
                   3000.5, 0.0]
````

At time zero, you have the full lead path showing of 3000.5 seconds.  At the end of the flight, at time 3000.5, you don't have any lead left, so the lead time is zero.  In this manner, the lead time decreases as time increases, and the end of the lead appears to remain fixed in time.  The same can be done in reverse for `trailTime`, except the trail would start at zero and end at 3000.5.

```
    "trailTime" : [ 0.0, 0.0,
                    3000.5, 3000.5]
````

In this case, the trail grows 1-to-1 over time as time increases, so the vehicle leaves behind a trail that appears to have a fixed-in-time start point.
