### ISSUE TITLE
Shapefile to CZML

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/czml-writer#3]

**Comment by hanokhaloni** [comment]
Hey, is there any shapefile to CZML convertor?

**Comment by pjcozzi** [comment]
There is a library.  For example, here are the tests: https://github.com/AnalyticalGraphicsInc/czml-writer/tree/master/DotNet/ShapefileToCesiumLanguageTests

**Comment by forman** [comment]
Hi! Any plans to add a command-line interface? Will also the czml-writer Java library support shapefiles one day?

**Comment by pjcozzi** [comment]
@forman there's no near-term plans for a command-line interface.  The Java library is generated from the C# library, and I'm not sure when the next update is expected, it could be a bit.

**Comment by shunter** [comment]
The current shapefile converter library has not been maintained, and was never ported to Java.  At this point I intend to limit the scope of this project to solely CZML generation, and I will be removing the converter code from this repository.  

Rather than providing converters to CZML, it would be better to spend effort in adding shapefile support directly to Cesium - see cesium#2750. This is the same approach we took with KML successfully.  

Alternatively, any interested parties are welcome to fork and maintain the shapefile code themselves, under the Apache license.
